In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import OneHotEncoder

In [ ]:
df = pd.read_csv("StudentsPerformance.csv")#import data
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [ ]:
#encoding into numerical data below

df["gender"] = df["gender"].map({
    "male":1,
    "female":0
})
df["race/ethnicity"] = df["race/ethnicity"].map({
    "group A":1,
    "group B":2,
    "group C":3,
    "group D":4,
    "group E":5
})
df = pd.get_dummies(df, columns=["parental level of education"],dtype=int)
df["test preparation course"] = df["test preparation course"].map({
    "none":0,
    "completed":1
})
df["lunch"] = df["lunch"].map({
    "standard":1,
    "free/reduced":0
})
df.head()

,gender,race/ethnicity,lunch,test preparation course,math score,reading score,writing score,parental level of education_associate's degree,parental level of education_bachelor's degree,parental level of education_high school,parental level of education_master's degree,parental level of education_some college,parental level of education_some high school
0,0,2,1,0,72,72,74,0,1,0,0,0,0
1,0,3,1,1,69,90,88,0,0,0,0,1,0
2,0,2,1,0,90,95,93,0,0,0,1,0,0
3,1,1,0,0,47,57,44,1,0,0,0,0,0
4,1,3,1,0,76,78,75,0,0,0,0,1,0

In [ ]:
#finding strongest correlations with math score(target variable)
corr = df.corr(numeric_only=True)["math score"]
print(corr)

gender                                            0.167982
race/ethnicity                                    0.216415
lunch                                             0.350877
test preparation course                           0.177702
math score                                        1.000000
reading score                                     0.817580
writing score                                     0.802642
parental level of education_associate's degree    0.063228
parental level of education_bachelor's degree     0.079664
parental level of education_high school          -0.128725
parental level of education_master's degree       0.060417
parental level of education_some college          0.037056
parental level of education_some high school     -0.079852
Name: math score, dtype: float64

In [ ]:
#training the model below

from sklearn.metrics import r2_score #importing r2_score for testing r^2 score

X = df.drop("math score",axis=1)#taking every feature except math score(target variable) as input
y = df["math score"]#output is maths score

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)#train-test-splitting
model = LinearRegression()#model class
model.fit(X,y)
prediction = model.predict(X_test)
print("Actual:")
print(y_test.values[:5])
print("predicted:")
print(prediction[:5])

print("The R^2 test value is: " , round(r2_score(prediction,y_test) , 1))

Actual:
[91 53 80 74 84]
predicted:
[77.57637432 57.06231855 78.71284527 77.68069908 84.76025948]
The R^2 test value is:  0.9